<?php
$z[0]=Array("global","",8,33);
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",38,53);
$z[2]=Array("global","",69,94);
$z[2][4]['name']="autoindex";
$z[3]=Array("litpic","",100,115);
$z[4]=Array("global","",132,157);
$z[4][4]['name']="autoindex";
$z[5]=Array("title","",162,202);
$z[5][4]['function']="html2text(@me)";
$z[6]=Array("global","",218,243);
$z[6][4]['name']="autoindex";
$z[7]=Array("shorttitle","",249,298);
$z[7][4]['function']="cn_substr(@me,100)";

?>