{dede:noteinfo notename="彩票销售公告" channelid="1" macthtype="string"
refurl="" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://info.sporttery.cn/iframe/lottery_notice.php"
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="SaleTxtBox">{/dede:areastart}
    {dede:areaend}<div class="page_3_right FloatR"> {/dede:areaend}
{/dede:listrule}
