<dl>
          <dt><a href="http://news.zhiying365.com[field:arcurl/]" target="_blank"><img src="[field:litpic/]" /></a><span><a href="http://news.zhiying365.com[field:arcurl/]" target="_blank">&nbsp;</a></span></dt>
          <dd>
            <p><a href="http://news.zhiying365.com[field:arcurl/]" target="_blank">[field:title function="( strlen('@me')>40 ? cn_substr('@me',40).'…' : '@me' )" /]</a></p>
            <p>[field:shorttitle/]</p>
          </dd>
        </dl>