
<field:focus_pic1 itemname="焦点图1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic1>

<field:focus_pic1_link itemname="焦点图1_链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic1_link>

<field:focus_pic1_title itemname="焦点图1_标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic1_title>

<field:focus_pic1_desc itemname="焦点图1_描述" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic1_desc>

<field:focus_pic2 itemname="焦点图2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic2>

<field:focus_pic2_link itemname="焦点图2_链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic2_link>

<field:focus_pic2_title itemname="焦点图2_标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic2_title>

<field:focus_pic2_desc itemname="焦点图2_描述" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic2_desc>

<field:focus_pic3 itemname="焦点图3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic3>

<field:focus_pic3_link itemname="焦点图3_链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic3_link>

<field:focus_pic3_title itemname="焦点图3_标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic3_title>

<field:focus_pic3_desc itemname="焦点图3_描述" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic3_desc>

<field:focus_pic4 itemname="焦点图4" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic4>

<field:focus_pic4_link itemname="焦点图4_链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic4_link>

<field:focus_pic4_title itemname="焦点图4_标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic4_title>

<field:focus_pic4_desc itemname="焦点图4_描述" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic4_desc>

<field:hot_bets itemname="今日热投" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:hot_bets>

<field:focus_news_title itemname="焦点新闻标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_news_title>

<field:focus_news_desc itemname="焦点新闻描述" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_news_desc>

<field:focus_news_list itemname="焦点新闻列表" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_news_list>

<field:mad_pic itemname="中部广告图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:mad_pic>

<field:mad_link itemname="中部广告链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:mad_link>
