<?php
$z[0]=Array("field","",106,125);
$z[0][4]['name']="title";
$z[1]=Array("global","",126,152);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",235,257);
$z[2][4]['name']="keywords";
$z[3]=Array("include","",855,889);
$z[3][4]['file']="header.htm";
$z[4]=Array("field","",998,1027);
$z[4][4]['name']="typelink";
$z[5]=Array("field","",1045,1074);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n          <li><strong>&bull;</strong><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></li>\r\n          ",1270,1466);
$z[6][4]['pagesize']="22";
$z[6][4]['titlelen']="60";
$z[6][4]['orderby']="id";
$z[6][4]['orderway']="desc";
$z[7]=Array("pagelist","",1544,1622);
$z[7][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[7][4]['listsize']="5";
$z[8]=Array("arclist","\r\n          <li><b>&bull;</b><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></li>\r\n          ",1789,2035);
$z[8][4]['channelid']="1";
$z[8][4]['typeid']="4,5,6,7,8";
$z[8][4]['titlelen']="50";
$z[8][4]['orderby']="click";
$z[8][4]['orderway']="desc";
$z[8][4]['row']="11";
$z[9]=Array("arclist","\r\n          <li><b>&bull;</b><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></li>\r\n          ",2170,2416);
$z[9][4]['channelid']="1";
$z[9][4]['typeid']="4,5,6,7,8";
$z[9][4]['titlelen']="50";
$z[9][4]['orderby']="click";
$z[9][4]['orderway']="desc";
$z[9][4]['row']="11";
$z[10]=Array("include","",2701,2735);
$z[10][4]['file']="footer.htm";

?>