
<field:focus_pic1 itemname="焦点图1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic1>

<field:focus_pic1_link itemname="焦点图1_链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic1_link>

<field:focus_pic2 itemname="焦点图2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic2>

<field:focus_pic2_link itemname="焦点图2_链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic2_link>

<field:focus_pic3 itemname="焦点图3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic3>

<field:focus_pic3_link itemname="焦点图3_链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic3_link>

<field:focus_pic4 itemname="焦点图4" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic4>

<field:focus_pic4_link itemname="焦点图4_链接" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:focus_pic4_link>

<field:quick_nav itemname="快速导航" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:quick_nav>

