<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div class="footer">
  <div id="gotop"><a href="javascript:void(0)">返回顶部</a></div>
  <div id="Rightsubnav">
    <ul>
      <li class="service"><a href="http://wpa.qq.com/msgrd?v=1&uin=2733292184&site=qq&menu=yes" target="_blank">在线客服</a></li>
      <li class="msg"><a href="http://www.zhiying365.com/message/show.php" target="_blank">留言智赢</a></li>
      <li class="help"><a href="http://www.zhiying365.com/help/" target="_blank">帮助中心</a></li>
    </ul>
  </div>
  <div class="footdaodu">
    <p><a href="/passport/reg.php" target="_blank">用户注册</a><span>|</span></p>
    <p><a href="/about/index.html" target="_blank">关于我们</a><span>|</span></p>
    <p><a href="/about/baozhang.html" target="_blank">安全保障</a><span>|</span></p>
    <p><a href="/about/contactus.html" target="_blank">联系方式</a><span>|</span></p>
    <p><a href="/about/job.html" target="_blank">人才招聘</a><span>|</span></p>
    <p><a href="/about/bd.html" target="_blank">商务合作</a><span>|</span></p>
    <p><a href="/about/lawfirm.html" target="_blank">法律声明</a><span>|</span></p>
    <p><a href="/about/xieyi.html" target="_blank">网站协议</a></p>
  </div>
  <div class="FooterOhter">
    <p>彩票有风险，投注需谨慎，不向未满18周岁的青少年出售彩票&nbsp;&nbsp;客服热线：010-57190959&nbsp;&nbsp;&nbsp;<a href="http://www.zhiying365.com/message/show.php" target="_blank">您的建议对我们很重要!</a></p>
  </div>
  <div class="FootPic">
    <ul>
      <li><a href="http://www.pinpaibao.com.cn/intro/index/" target="_blank"><img src="http://www.zhiying365.com/www/statics/i/FootPic2.jpg"/></a></li>
      <li><a href="http://www.miitbeian.gov.cn/state/outPortal/loginPortal.action" target="_blank"><img src="http://www.zhiying365.com/www/statics/i/FootPic1.jpg"/></a></li>
      <li><a href="http://www.315online.com.cn/" target="_blank"><img src="http://www.zhiying365.com/www/statics/i/FootPic3.jpg"/></a></li>
      <li><a href="http://www.mps.gov.cn/n16/index.html?_v=1438535553945" target="_blank"><img src="http://www.zhiying365.com/www/statics/i/FootPic4.jpg"/></a></li>
      <li><a href="http://www.itrust.org.cn/" target="_blank"><img src="http://www.zhiying365.com/www/statics/i/FootPic5.jpg"/></a></li>
      <li><a href="http://www.bj.cyberpolice.cn/index.jsp" target="_blank"><img src="http://www.zhiying365.com/www/statics/i/FootPic6.jpg"/></a></li>
    </ul>
  </div>
  <div class="FooterOhter">
  	<p>2014-2016&nbsp;智赢网&nbsp;&copy;&nbsp;版权所有&nbsp;All rights reserved</p>
    <p>京ICP备14016851-1号</p>
    <p>京ICP证150586号</p>
    <p>京公安网备11011402000202</p>
  </div>
</div>
<div class="none">
  <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https:\/\/" : " http:\/\/");document.write(unescape("%3Cspan id='cnzz_stat_icon_1000441119'%3E%3C\/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com\/z_stat.php%3Fid%3D1000441119%26show%3Dpic' type='text\/javascript'%3E%3C\/script%3E"));</script>
</div>
<div class="none">
  <script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?b5c0fa192dddf3552c42bd96791a0a00";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
</div>
<script src="http://www.zhiying365.com/www/statics/j/pms.js"></script>
<script src="http://www.zhiying365.com/www/statics/j/float.js"></script>
<script src="http://www.zhiying365.com/www/statics/j/navigator.js"></script>