<?php
$z[0]=Array("include","",906,940);
$z[0][4]['file']="header.htm";
$z[1]=Array("arclist","\r\n      <li>\r\n        <h3><em>&nbsp;</em><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a><span>[field:pubdate function='strftime(\"%m-%d\",@me)'/]</span></h3>\r\n        <dl>\r\n          <dt>[field:description function='cn_substr(@me,700)'/] ...<a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">详细...</a></dt>\r\n        </dl>\r\n      </li>\r\n      ",1121,1640);
$z[1][4]['channelid']="1";
$z[1][4]['typeid']="11";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[1][4]['row']="25";
$z[1][4]['addfields']="body";
$z[2]=Array("include","",1690,1724);
$z[2][4]['file']="footer.htm";

?>