<?php
$z[0]=Array("include","",868,902);
$z[0][4]['file']="header.htm";
$z[1]=Array("arclist","\r\n      <li>\r\n        <h4><em>&nbsp;</em><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a><span>[field:pubdate function='strftime(\"%m-%d\",@me)'/]</span></h4>\r\n        <dl>\r\n          <dt>[field:description function='cn_substr(@me,700)'/] ...</dt>\r\n        </dl>\r\n      </li>\r\n      ",1101,1524);
$z[1][4]['channelid']="1";
$z[1][4]['typeid']="47";
$z[1][4]['titlelen']="46";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[1][4]['row']="25";
$z[2]=Array("include","",1574,1608);
$z[2][4]['file']="footer.htm";

?>