<?php
$z[0]=Array("field","",35,54);
$z[0][4]['name']="title";
$z[1]=Array("global","",55,81);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("arclist","\r\n<div class=\"zhongchainews\">\r\n  <dl>\r\n    <dt><a href=\"[field:arcurl/]\">[field:title function=\"( strlen('@me')>150 ? cn_substr('@me',150).'…' : '@me' )\" /]</a></dt>\r\n    <dd>[field:description function='cn_substr(@me,500)'/] ...</dd>\r\n	<dd class=\"show\"><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl/]\">详情</a></dd>\r\n  </dl>\r\n</div>\r\n",1692,2173);
$z[2][4]['channelid']="1";
$z[2][4]['typeid']="48";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="id";
$z[2][4]['orderway']="desc";
$z[2][4]['row']="15";
$z[3]=Array("pagelist","",2193,2271);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="5";
$z[4]=Array("include","",2288,2325);
$z[4][4]['file']="wap_footer.htm";

?>