<?php
$z[0]=Array("field","",2584,2603);
$z[0][4]['name']="body";
$z[1]=Array("arclist","\r\n      <dl>\r\n        <dt><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" /></a><span><a href=\"[field:arcurl/]\" target=\"_blank\">&nbsp;</a></span></dt>\r\n        <dd>\r\n          <p><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title function=\"( strlen('@me')>40 ? cn_substr('@me',40).'…' : '@me' )\" /]</a></p>\r\n           <p>[field:shorttitle/]</p>\r\n        </dd>\r\n      </dl>\r\n      ",2717,3250);
$z[1][4]['channelid']="1";
$z[1][4]['typeid']="29";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[1][4]['row']="18";
$z[1][4]['addfields']="body";

?>