<?php
$z[0]=Array("arclist","\r\n        [field:body/]\r\n        \r\n        ",2920,3098);
$z[0][4]['channelid']="1";
$z[0][4]['typeid']="31";
$z[0][4]['titlelen']="50";
$z[0][4]['orderby']="id";
$z[0][4]['orderway']="desc";
$z[0][4]['row']="1";
$z[0][4]['limit']="0,1";
$z[0][4]['addfields']="body";
$z[1]=Array("arclist","\r\n        <dl>\r\n          <dt><a href=\"http://news.zhiying365.com[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" /></a><span><a href=\"http://news.zhiying365.com[field:arcurl/]\" target=\"_blank\">&nbsp;</a></span></dt>\r\n          <dd>\r\n            <p><a href=\"http://news.zhiying365.com[field:arcurl/]\" target=\"_blank\">[field:title function=\"( strlen('@me')>40 ? cn_substr('@me',40).'…' : '@me' )\" /]</a></p>\r\n            <p>[field:shorttitle/]</p>\r\n          </dd>\r\n        </dl>\r\n        ",3140,3747);
$z[1][4]['channelid']="1";
$z[1][4]['typeid']="32";
$z[1][4]['titlelen']="46";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[1][4]['row']="6";
$z[2]=Array("arclist","\r\n      <dl>\r\n        <dt><a href=\"http://news.zhiying365.com[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" /></a><span><a href=\"[field:arcurl/]\" target=\"_blank\">&nbsp;</a></span></dt>\r\n        <dd>\r\n          <p><a href=\"http://news.zhiying365.com[field:arcurl/]\" target=\"_blank\">[field:title function=\"( strlen('@me')>40 ? cn_substr('@me',40).'…' : '@me' )\" /]</a></p>\r\n          <p>[field:shorttitle/]</p>\r\n        </dd>\r\n      </dl>\r\n      ",3909,4493);
$z[2][4]['channelid']="1";
$z[2][4]['typeid']="29";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="id";
$z[2][4]['orderway']="desc";
$z[2][4]['row']="25";
$z[2][4]['addfields']="body";

?>