<?php
$z[0]=Array("field","",30,49);
$z[0][4]['name']="title";
$z[1]=Array("global","",50,76);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",1349,1368);
$z[2][4]['name']="title";
$z[3]=Array("field","",1402,1456);
$z[3][4]['name']="pubdate";
$z[3][4]['function']="MyDate('Y-m-d', @me)";
$z[4]=Array("field","",1493,1513);
$z[4][4]['name']="source";
$z[5]=Array("field","",1545,1564);
$z[5][4]['name']="body";
$z[6]=Array("include","",1581,1618);
$z[6][4]['file']="wap_footer.htm";

?>