<?php
$z[0]=Array("arclist","\r\n        <li>\r\n          <p><span>[喜报]</span>[field:title/]</p>\r\n        </li>\r\n        ",2266,2466);
$z[0][4]['channelid']="1";
$z[0][4]['typeid']="10";
$z[0][4]['titlelen']="40";
$z[0][4]['orderby']="id";
$z[0][4]['orderway']="desc";
$z[0][4]['row']="22";
$z[1]=Array("arclist","\r\n        <li>\r\n          <p><span>[公告]</span><a href=\"http://new.shunjubao.xyz/[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></p>\r\n        </li>\r\n        ",2486,2784);
$z[1][4]['channelid']="1";
$z[1][4]['typeid']="11";
$z[1][4]['titlelen']="40";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[1][4]['row']="1";
$z[2]=Array("include","",8471,8508);
$z[2][4]['file']="wap_footer.htm";

?>