<?php
$z[0]=Array("arclist","\n        <li>\n          <p><span>[喜报]</span>[field:title/]</p>\n        </li>\n        ",2385,2581);
$z[0][4]['channelid']="1";
$z[0][4]['typeid']="10";
$z[0][4]['titlelen']="40";
$z[0][4]['orderby']="id";
$z[0][4]['orderway']="desc";
$z[0][4]['row']="22";
$z[1]=Array("arclist","\n        <li>\n          <p><span>[公告]</span><a href=\"http://news.zhiying365.com/[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></p>\n        </li>\n        ",2599,2890);
$z[1][4]['channelid']="1";
$z[1][4]['typeid']="11";
$z[1][4]['titlelen']="40";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[1][4]['row']="1";
$z[2]=Array("include","",8289,8326);
$z[2][4]['file']="wap_footer.htm";

?>