<?php
$z[0]=Array("field","",30,49);
$z[0][4]['name']="title";
$z[1]=Array("global","",50,76);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",1361,1380);
$z[2][4]['name']="title";
$z[3]=Array("field","",1414,1468);
$z[3][4]['name']="pubdate";
$z[3][4]['function']="MyDate('Y-m-d', @me)";
$z[4]=Array("field","",1505,1525);
$z[4][4]['name']="source";
$z[5]=Array("field","",1557,1576);
$z[5][4]['name']="body";
$z[6]=Array("include","",1593,1630);
$z[6][4]['file']="wap_footer.htm";

?>