<?php
$z[0]=Array("field","",103,122);
$z[0][4]['name']="title";
$z[1]=Array("global","",123,149);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1146,1180);
$z[2][4]['file']="header.htm";
$z[3]=Array("list","\r\n        <p><span>•</span><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a><em>[field:pubdate function='strftime(\"%m-%d\",@me)'/]</em></p>\r\n        ",1415,1679);
$z[3][4]['pagesize']="22";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="id";
$z[3][4]['orderway']="desc";
$z[4]=Array("pagelist","",1819,1897);
$z[4][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[4][4]['listsize']="5";
$z[5]=Array("myad","",2162,2189);
$z[5][4]['name']="hongren";
$z[6]=Array("include","",2851,2885);
$z[6][4]['file']="footer.htm";

?>