<?php
$z[0]=Array("field","",151,170);
$z[0][4]['name']="title";
$z[1]=Array("global","",171,197);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",340,362);
$z[2][4]['name']="keywords";
$z[3]=Array("include","",868,902);
$z[3][4]['file']="header.htm";
$z[4]=Array("field","",972,991);
$z[4][4]['name']="title";
$z[5]=Array("field","",1019,1073);
$z[5][4]['name']="pubdate";
$z[5][4]['function']="MyDate('Y-m-d', @me)";
$z[6]=Array("field","",1190,1209);
$z[6][4]['name']="body";
$z[7]=Array("include","",1244,1278);
$z[7][4]['file']="footer.htm";

?>