<?php
$z[0]=Array("arclist","\r\n        <dl>\r\n          <dt><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title function=\"( strlen('@me')>60 ? cn_substr('@me',40).'…' : '@me' )\" /]</a><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span></dt>\r\n          <dd>[field:info/]<a href=\"[field:arcurl/]\" target=\"_blank\">详细</a></dd>\r\n        </dl>\r\n        ",1454,1894);
$z[0][4]['channelid']="1";
$z[0][4]['typeid']="41";
$z[0][4]['titlelen']="50";
$z[0][4]['orderby']="id";
$z[0][4]['orderway']="desc";
$z[0][4]['row']="40";
$z[1]=Array("pagelist","",1957,2035);
$z[1][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[1][4]['listsize']="5";

?>