<?php
$z[0]=Array("field","",32,51);
$z[0][4]['name']="title";
$z[1]=Array("global","",52,78);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("arclist","\r\n<div class=\"zhongchainews\">\r\n  <dl>\r\n    <dt><a href=\"[field:arcurl/]\">[field:title function=\"( strlen('@me')>60 ? cn_substr('@me',50).'…' : '@me' )\" /]</a><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span></dt>\r\n    <dd>[field:info/]<a href=\"[field:arcurl/]\">详细</a></dd>\r\n  </dl>\r\n</div>\r\n",2118,2531);
$z[2][4]['channelid']="1";
$z[2][4]['typeid']="40";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="id";
$z[2][4]['orderway']="desc";
$z[2][4]['row']="80";
$z[3]=Array("pagelist","",2551,2629);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="5";

?>