<?php
$z[0]=Array("field","",32,51);
$z[0][4]['name']="title";
$z[1]=Array("global","",52,78);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",2256,2275);
$z[2][4]['name']="title";
$z[3]=Array("field","",2309,2363);
$z[3][4]['name']="pubdate";
$z[3][4]['function']="MyDate('Y-m-d', @me)";
$z[4]=Array("field","",2400,2420);
$z[4][4]['name']="source";
$z[5]=Array("field","",2452,2471);
$z[5][4]['name']="body";

?>