<?php
$z[0]=Array("arclist","\r\n            <p><span>●</span><a href=\"http://news.zhiying365.com[field:arcurl/]\">[field:title function=\"( strlen('@me')>60 ? cn_substr('@me',40).'…' : '@me' )\" /]</a></p>\r\n            ",3146,3443);
$z[0][4]['channelid']="1";
$z[0][4]['typeid']="40";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="id";
$z[0][4]['orderway']="desc";
$z[0][4]['row']="12";
$z[1]=Array("arclist","\r\n            <p><span>●</span><a href=\"http://news.zhiying365.com[field:arcurl/]\">[field:title function=\"( strlen('@me')>60 ? cn_substr('@me',40).'…' : '@me' )\" /]</a></p>\r\n            ",4000,4297);
$z[1][4]['channelid']="1";
$z[1][4]['typeid']="41";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[1][4]['row']="12";

?>