<?php
$z[0]=Array("arclist"," <a href=\"http://news.zhiying365.com[field:arcurl/]\" target=\"_blank\">&nbsp;</a> <a href=\"http://news.zhiying365.com[field:arcurl/]\" target=\"_blank\">[field:title function=\"( strlen('@me')>40 ? cn_substr('@me',40).'…' : '@me' )\" /]</a> ",1429,1771);
$z[0][4]['channelid']="1";
$z[0][4]['typeid']="37";
$z[0][4]['titlelen']="46";
$z[0][4]['orderby']="id";
$z[0][4]['orderway']="desc";
$z[0][4]['row']="6";

?>